# -*- coding: utf-8 -*-
"""AI_Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vZdpgdQ5fXGBP4WNsWJLRJEXtQf_w2sN
"""

import streamlit as st
import pandas as pd
import os
from langchain_community.document_loaders import PyPDFLoader
from langchain_cohere import ChatCohere
from langchain_core.prompts import ChatPromptTemplate



def preparar_conocimiento(archivos_pdf, tamano_chunk=600, solapamiento=100):
    chunks_totales = []

    for ruta_pdf in archivos_pdf:
        if not os.path.exists(ruta_pdf):
            print(f"⚠️ Alerta: No se encontró el archivo {ruta_pdf}, saltando...")
            continue

        try:
            lector = pypdf.PdfReader(ruta_pdf)
            texto_completo = ""
            for pagina in lector.pages:
                texto_pagina = pagina.extract_text()
                if texto_pagina:
                    texto_completo += texto_pagina + "\n"


            texto_completo = " ".join(texto_completo.split())


            inicio = 0
            while inicio < len(texto_completo):
                fin = inicio + tamano_chunk
                chunk = texto_completo[inicio:fin]

                chunks_totales.append(f"[{os.path.basename(ruta_pdf)}]: {chunk}")
                inicio += tamano_chunk - solapamiento

        except Exception as e:
            print(f"Error procesando {ruta_pdf}: {e}")

    return chunks_totales


documentos_a_leer = [
    "/content/politicas_hotel_tranquipets.pdf",
    "/content/faq_preguntas-frecuentes.pdf"
]

print("⏳ Procesando tus PDFs y extrayendo fragmentos...")
mis_chunks = preparar_conocimiento(documentos_a_leer)
print(f"✅ Éxito: Se generaron {len(mis_chunks)} fragmentos de conocimiento listos para el asistente.\n")


try:
    api_key = userdata.get('COHERE_API_KEY')
    co = cohere.ClientV2(api_key=api_key)

    MODELO_CHAT = "command-r-plus-08-2024"

    def chat_asistente_experto():
        print("🤖 ¡Asistente activado! Conozco las políticas de Tranquipets y tus FAQs.")
        print("Hazme una pregunta sobre las reglas, horarios o servicios. (Escribe 'salir' para terminar).\n" + "="*60)

        historial_chat = []

        while True:
            pregunta = input("👤 Tú: ")
            if pregunta.lower() == 'salir':
                print("🤖 Asistente: ¡Hasta luego! Que tengas un excelente día.")
                break
            if not pregunta.strip():
                continue

            try:

                print("🔍 Buscando en los PDFs...")
                busqueda = co.rerank(
                    model="rerank-v3.5",
                    query=pregunta,
                    documents=mis_chunks,
                    top_n=4
                )


                contexto_relevante = ""
                for resultado in busqueda.results:
                    contexto_relevante += mis_chunks[resultado.index] + "\n\n"


                prompt_sistema = (
                    "Eres un asistente de atención al cliente experto. Tu deber es responder la pregunta del usuario "
                    "basándote ÚNICAMENTE en los fragmentos de los documentos proporcionados a continuación. "
                    "Si la respuesta no se encuentra en la información proporcionada, di amablemente que no posees esa "
                    "información y ofrece derivar con un humano. No inventes datos.\n\n"
                    f"--- DOCUMENTOS DE REFERENCIA ---\n{contexto_relevante}"
                )


                mensajes_api = [{"role": "system", "content": prompt_sistema}]

                mensajes_api.extend(historial_chat)

                mensajes_api.append({"role": "user", "content": pregunta})


                respuesta = co.chat(
                    model=MODELO_CHAT,
                    messages=mensajes_api
                )

                texto_respuesta = respuesta.message.content[0].text
                print(f"\n🤖 Asistente:\n{texto_respuesta}\n" + "="*60)


                historial_chat.append({"role": "user", "content": pregunta})
                historial_chat.append({"role": "assistant", "content": texto_respuesta})

            except Exception as e:
                print(f"🚨 Error durante la consulta: {e}\n" + "="*60)


    if mis_chunks:
        chat_asistente_experto()
    else:
        print("❌ No se puede iniciar el chat porque no se cargaron fragmentos de texto.")

except userdata.SecretNotFoundError:
    print("🚨 ERROR: Configura el secreto 'COHERE_API_KEY' en el menú de la llave 🔑.")
